default:
  image: hub.netrtl.com/public/redo:1
  tags:
    - k8s-managed-devops
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

variables:
  ARGOCD_PROJECT: cvdt/hackathon/argocd-internal

stages:
  - build
  - deploy-vars
  - deploy-dev

include:
  - project: templates/ci/redo
    file: /jobs/version-update.gitlab-ci.yml
  - project: templates/ci/redo
    file: /jobs/version-commit.gitlab-ci.yml
  - component: gitlab.netrtl.com/templates/ci/component/argocd/deploy@0
    inputs:
      step: deploy-dev
      stage: deploy-dev
      argocd_app_dir: apps/productspecagent/dev
      argocd_app_values: values.yaml
      when: always

docker-build:
  stage: build
  script:
    - redo docker:build docker:push -Dproject_name=$PROJECT_DIR -Ddocker_build_ctx=$PROJECT_DIR -Ddocker_build_file=$PROJECT_DIR/Dockerfile
  rules:
    - if: $CI_COMMIT_BRANCH
  parallel:
    matrix:
      - PROJECT_DIR: backend
      - PROJECT_DIR: frontend

deploy-vars:
  stage: deploy-vars
  script:
    - redo write -Dfrom=deploy-vars.tpl.env -Dto=deploy-vars.env
  artifacts:
    reports:
      dotenv: deploy-vars.env
  only:
    - tags
