redo:
  properties:
    project_name: "backend"
    project_on_start: "clean:dist"
    project_on_commit: "clean:dist"
    project_on_update: "clean:dist"
    project_on_install: "clean:dist"
    docker_registry: "hub.netrtl.com"
    docker_registry_namespace: "cvdt/hackathon/product-spec-agent"
    docker_build_file: "backend/Dockerfile"
    docker_build_ctx: "backend"

  branches:
    main:
      regex: "^main$"
      docker_push:
        - "{{ docker_tag_rolling_patch }}"
