package com.agentwork.productspecagent.export

import com.agentwork.productspecagent.domain.*
import com.agentwork.productspecagent.service.*
import org.springframework.stereotype.Service
import java.io.ByteArrayOutputStream
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

@Service
class ExportService(
    private val projectService: ProjectService,
    private val decisionService: DecisionService,
    private val clarificationService: ClarificationService,
    private val taskService: TaskService
) {
    fun exportProject(projectId: String, request: ExportRequest = ExportRequest()): ByteArray {
        val projectResponse = projectService.getProject(projectId)
        val project = projectResponse.project
        val flowState = projectResponse.flowState
        val prefix = project.name.lowercase().replace(Regex("[^a-z0-9]+"), "-").trim('-')

        val baos = ByteArrayOutputStream()
        ZipOutputStream(baos).use { zip ->
            // README.md
            zip.addEntry("$prefix/README.md", generateReadme(project, flowState))

            // SPEC.md — combine all spec steps
            zip.addEntry("$prefix/docs/SPEC.md", generateSpec(projectId, flowState))

            // .gitignore
            zip.addEntry("$prefix/.gitignore", ".DS_Store\nnode_modules/\n.env\n")

            // Docs scaffold + Uploads (alle Dateien unter docs/ einschliesslich Binärdateien)
            for ((relativePath, content) in projectService.listDocsFiles(projectId)) {
                zip.addBinaryEntry("$prefix/$relativePath", content)
            }

            // Decisions
            if (request.includeDecisions) {
                val decisions = decisionService.listDecisions(projectId)
                if (decisions.isNotEmpty()) {
                    decisions.forEachIndexed { i, d ->
                        val slug = d.title.lowercase().replace(Regex("[^a-z0-9]+"), "-").trim('-').take(50)
                        zip.addEntry("$prefix/docs/decisions/${String.format("%03d", i + 1)}-$slug.md", generateDecisionMd(d))
                    }
                }
            }

            // Clarifications
            if (request.includeClarifications) {
                val clarifications = clarificationService.listClarifications(projectId)
                if (clarifications.isNotEmpty()) {
                    clarifications.forEachIndexed { i, c ->
                        val slug = c.question.lowercase().replace(Regex("[^a-z0-9]+"), "-").trim('-').take(50)
                        zip.addEntry("$prefix/docs/clarifications/${String.format("%03d", i + 1)}-$slug.md", generateClarificationMd(c))
                    }
                }
            }

            // Tasks / Plan
            if (request.includeTasks) {
                val tasks = taskService.listTasks(projectId)
                if (tasks.isNotEmpty()) {
                    zip.addEntry("$prefix/docs/PLAN.md", generatePlanMd(tasks))
                    tasks.forEachIndexed { i, t ->
                        val slug = t.title.lowercase().replace(Regex("[^a-z0-9]+"), "-").trim('-').take(50)
                        val typePrefix = t.type.name.lowercase()
                        zip.addEntry("$prefix/docs/tasks/${String.format("%03d", i + 1)}-$typePrefix-$slug.md", generateTaskMd(t))
                    }
                }
            }

        }

        return baos.toByteArray()
    }

    private fun generateReadme(project: Project, flowState: FlowState): String = buildString {
        appendLine("# ${project.name}")
        appendLine()
        appendLine("## Status")
        appendLine("Current step: ${flowState.currentStep.name}")
        appendLine()
        appendLine("## Structure")
        appendLine("- `docs/SPEC.md` — Full product specification")
        appendLine("- `docs/PLAN.md` — Implementation plan with tasks")
        appendLine("- `docs/decisions/` — Key product decisions")
        appendLine("- `docs/clarifications/` — Clarified requirements")
        appendLine("- `docs/tasks/` — Individual task files")
        appendLine("- `docs/uploads/` — Original uploaded documents")
        appendLine()
        appendLine("## Flow Progress")
        for (step in flowState.steps) {
            val icon = when (step.status) {
                FlowStepStatus.COMPLETED -> "[x]"
                FlowStepStatus.IN_PROGRESS -> "[-]"
                FlowStepStatus.OPEN -> "[ ]"
            }
            appendLine("- $icon ${step.stepType.name}")
        }
        appendLine()
        appendLine("---")
        appendLine("Generated by Product Spec Agent")
    }

    private fun generateSpec(projectId: String, flowState: FlowState): String = buildString {
        appendLine("# Product Specification")
        appendLine()

        // Include auto-generated spec.md if it exists
        val autoSpec = projectService.readSpecFile(projectId, "spec.md")
        if (autoSpec != null) {
            appendLine(autoSpec)
            appendLine()
            appendLine("---")
            appendLine()
        }

        // Include individual step files
        for (step in flowState.steps) {
            val fileName = step.stepType.name.lowercase() + ".md"
            val content = projectService.readSpecFile(projectId, fileName)
            if (content != null) {
                appendLine(content)
                appendLine()
                appendLine("---")
                appendLine()
            }
        }
    }

    private fun generateDecisionMd(d: Decision): String = buildString {
        appendLine("---")
        appendLine("status: ${d.status.name}")
        appendLine("step: ${d.stepType.name}")
        appendLine("created: ${d.createdAt}")
        if (d.resolvedAt != null) appendLine("resolved: ${d.resolvedAt}")
        appendLine("---")
        appendLine()
        appendLine("# ${d.title}")
        appendLine()
        appendLine("## Options")
        for (opt in d.options) {
            appendLine("### ${opt.label}${if (opt.recommended) " ⭐ Recommended" else ""}")
            appendLine("**Pros:** ${opt.pros.joinToString(", ")}")
            appendLine("**Cons:** ${opt.cons.joinToString(", ")}")
            appendLine()
        }
        appendLine("## Recommendation")
        appendLine(d.recommendation)
        if (d.status == DecisionStatus.RESOLVED) {
            appendLine()
            appendLine("## Decision")
            val chosen = d.options.find { it.id == d.chosenOptionId }
            appendLine("**Chosen:** ${chosen?.label ?: d.chosenOptionId}")
            appendLine("**Rationale:** ${d.rationale}")
        }
    }

    private fun generateClarificationMd(c: Clarification): String = buildString {
        appendLine("---")
        appendLine("status: ${c.status.name}")
        appendLine("step: ${c.stepType.name}")
        appendLine("created: ${c.createdAt}")
        if (c.answeredAt != null) appendLine("answered: ${c.answeredAt}")
        appendLine("---")
        appendLine()
        appendLine("# ${c.question}")
        appendLine()
        appendLine("**Why this matters:** ${c.reason}")
        if (c.answer != null) {
            appendLine()
            appendLine("## Answer")
            appendLine(c.answer)
        }
    }

    private fun generatePlanMd(tasks: List<SpecTask>): String = buildString {
        appendLine("# Implementation Plan")
        appendLine()
        val epics = tasks.filter { it.type == TaskType.EPIC }
        for (epic in epics) {
            appendLine("## ${epic.title}")
            appendLine(epic.description)
            appendLine()
            val stories = tasks.filter { it.parentId == epic.id }
            for (story in stories) {
                appendLine("### ${story.title}")
                appendLine(story.description)
                appendLine()
                val subtasks = tasks.filter { it.parentId == story.id }
                for (task in subtasks) {
                    appendLine("- [ ] **${task.title}** (${task.estimate}) — ${task.description}")
                }
                appendLine()
            }
        }
    }

    private fun generateTaskMd(t: SpecTask): String = buildString {
        appendLine("---")
        appendLine("type: ${t.type.name}")
        appendLine("status: ${t.status.name}")
        appendLine("estimate: ${t.estimate}")
        appendLine("priority: ${t.priority}")
        if (t.parentId != null) appendLine("parent: ${t.parentId}")
        if (t.specSection != null) appendLine("spec-section: ${t.specSection.name}")
        if (t.dependencies.isNotEmpty()) appendLine("dependencies: ${t.dependencies.joinToString(", ")}")
        appendLine("---")
        appendLine()
        appendLine("# ${t.title}")
        appendLine()
        appendLine(t.description)
    }

    private fun ZipOutputStream.addEntry(name: String, content: String) {
        putNextEntry(ZipEntry(name))
        write(content.toByteArray())
        closeEntry()
    }

    private fun ZipOutputStream.addBinaryEntry(name: String, content: ByteArray) {
        putNextEntry(ZipEntry(name))
        write(content)
        closeEntry()
    }
}
